# Generated by Django 3.1.1 on 2020-09-05 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20200905_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='nit',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.IntegerField(unique=True),
        ),
    ]
