# Generated by Django 3.1.1 on 2020-09-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20200905_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='nit',
            field=models.IntegerField(),
        ),
    ]
